config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#home'

  resources :locations, only: %i[new show create] do
    collection do
      get :expired
    end
    resources :clients, only: %i[create]
  end

  get '/legal', to: 'application#legal'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Preview error pages
  get '/errors/404', to: 'errors#not_found'
  get '/errors/500', to: 'errors#internal_server_error'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clients
#
#  id          :integer          not null, primary key
#  color       :string           not null
#  coordinates :string           not null
#  name        :string           not null
#  uuid        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  location_id :integer          not null
#
# Indexes
#
#  index_clients_on_location_id  (location_id)
#
# Foreign Keys
#
#  location_id  (location_id => locations.id)
#
class Client < ApplicationRecord
  COLORS = {
    stone: '#78716c',
    red: '#ef4444',
    orange: '#f97316',
    amber: '#f59e0b',
    yellow: '#eab308',
    green: '#15803d',
    lime: '#84cc16',
    emerald: '#22c55e',
    teal: '#10b981',
    cyan: '#14b8a6',
    sky: '#0ea5e9',
    blue: '#3b82f6',
    indigo: '#6366f1',
    violet: '#8b5cf6',
    purple: '#a855f7',
    fuchsia: '#d946ef',
    pink: '#ec4899',
    rose: '#f43f5e'
  }.freeze

  before_validation do |record|
    record.name = Client::COLORS.invert[record.color].to_s.capitalize if record.name.blank?
  end
  belongs_to :location, optional: true

  validates :name, :color, :uuid, presence: true

  validates :coordinates, presence: { message: 'could not be determined. Please enable location services.' }
end

app/models/dice_word.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: dice_words
#
#  id         :integer          not null, primary key
#  words      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class DiceWord < ApplicationRecord
  def readonly?
    true
  end
end

app/models/location.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: locations
#
#  id           :integer          not null, primary key
#  client_count :integer          default(0), not null
#  expires_at   :datetime         not null
#  expiry       :integer          not null
#  key          :string           not null
#  location     :string           not null
#  name         :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_locations_on_key  (key) UNIQUE
#
class Location < ApplicationRecord
  before_validation do |record|
    record.expires_at = record.expiry.minutes.from_now if record.expires_at.blank?
    record.key = Location.generate_key if record.key.blank?
  end

  has_many :clients, dependent: :destroy

  validates :key, :name, presence: true
  validates :expiry, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 180 }
  validates :expires_at, presence: true
  validates :location, presence: true

  after_destroy do |record|
    LocationChannel.broadcast_to(record, { event: 'locationDestroyed' })
  end

  def minutes_left
    ((expires_at - Time.zone.now) / 1.minute).to_i
  end

  def to_param
    key
  end

  def self.generate_key
    ids = (1..3).map { (1..5).map { rand(1..6) }.join.to_i }
    DiceWord
      .find(*ids)
      .map(&:words)
      .map(&:split)
      .map { |t| t[rand(0..t.length - 1)] }.flatten.join('-')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def home; end

  def legal; end
end

app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  before_action :set_location

  def create
    @client = @location.clients.build(client_params)

    respond_to do |format|
      if @client.save
        LocationChannel.broadcast_to(@location, { event: 'clientConnected', **client_params })
        Turbo::StreamsChannel
          .broadcast_prepend_to(
            @location,
            partial: 'layouts/flash',
            locals: { flash: { notice: "#{@client.name} joined this location" } },
            target: 'flash'
          )
        format.html { redirect_to location_url(@location), notice: 'You joined this location.' }
        format.turbo_stream { flash.now[:notice] = 'You joined this location.' }
      else
        flash.now[:alert] = @client.errors.full_messages.join(', ')
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  private

  def set_location
    @location = Location.find_by!(key: params[:location_id])
  end

  def client_params
    params.require(:client).permit(:name, :color, :coordinates, :uuid)
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: :not_found }
      format.json { render json: { error: 'not_found' }, status: :not_found }
    end
  end

  def internal_server_error
    respond_to do |format|
      format.html { render status: :internal_server_error }
      format.json { render json: { error: 'server_error' }, status: :internal_server_error }
    end
  end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  before_action :set_location, only: %i[show]

  def show
    session[:uuid] ||= SecureRandom.uuid
    @client = Client.new(uuid: session[:uuid])
  end

  def new
    @location = Location.new(expiry: 60)
  end

  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.all { redirect_to location_url(@location), notice: "Location '#{@location.name}' created." }
      else
        flash.now[:alert] = @location.errors.full_messages.join(', ')
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def expired; end

  private

  def set_location
    @location = Location.find_by!(key: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(:name, :expiry, :location)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def link_classes
    'underline font-medium hover:no-underline active:text-gray-500'
  end

  def flash_classes(flash_type)
    case flash_type
    when :notice
      'bg-blue-100 border-blue-400 text-blue-700'
    when :success
      'bg-green-100 border-green-400 text-green-700'
    when :warning
      'bg-yellow-100 border-yellow-400 text-yellow-700'
    when :alert
      'bg-red-100 border-red-400 text-red-700'
    else
      'bg-gray-100 border-gray-400 text-gray-700'
    end
  end
end

app/helpers/client_helper.rb
# frozen_string_literal: true

module ClientHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/views/application/home.html.erb
<section class="">
  <div class=" mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:items-center ">
    <div class="mx-auto text-center">
      <h1 class="font-bold text-4xl sm:text-7xl sm:leading-tight">
        <p
          class="
            bg-gradient-to-r from-cyan-400 via-purple-400 to-rose-400 inline-block
            text-transparent bg-clip-text
          "
        >Share Your Location.</p>
        <p class="text-3xl sm:text-6xl">Not Your Identity.</p>
      </h1>
      <p class="mx-auto max-w-2xl mt-4 sm:text-xl">
        Use Anonymous Location to share your position with anyone, over any
        channel. In real-time.
      </p>

      <div class="mt-8 flex flex-wrap justify-center gap-4">
        <a
          class="
            block text-gray-900 font-semibold outline-none bg-white w-full rounded-full
            transition px-12 py-3 text-sm focus:outline-none focus:ring sm:w-auto border
          "
          href="<%= new_location_path %>"
        >
          Get started
        </a>

        <a
          class="
            block w-full rounded-full border border-white px-12 py-3 text-sm
            background-white font-medium focus:outline-none focus:ring sm:w-auto
          "
          href="#how-it-works"
        >
          How it works
        </a>
      </div>
      <div class="max-w-4xl mx-auto w-full mt-16 relative">
        <div
          class="
            absolute -inset-1 bg-gradient-to-r from-cyan-400 to-rose-400 blur opacity-75
            animate-tilt
          "
        ></div>
        <%= image_tag "hero.png",
        class:
          "relative w-full rounded inset-0 object-cover bg-gradient-to-r from-cyan-400 to-rose-400" %>
      </div>

    </div>
  </div>
</section>
<section id="how-it-works" class="">

  <div class="container mx-auto max-w-screen-xl p-4 py-24 ">

    <p class="text-lg text-teal-400 font-bold sm:text-2xl mb-4 uppercase">How It Works</p>
    <h2 class="text-3xl font-semibold sm:text-5xl">Share Locations</h2>
    <div
      class="
        py-16 grid grid-cols-1 gap-8 items-center justify-between md:grid-cols-4
      "
    >

      <p class="text-8xl font-extrabold mb-4 text-teal-400">01</p>
      <div class="col-span-3">
        <h3 class="text-3xl font-semibold mb-2">Create location</h3>
        <p class="mb-4">
          Create a new location by dropping a pin on a map or sharing your
          position. You'll be given a unique URL to share.
        </p>
      </div>

      <p class="text-8xl font-extrabold mb-4 text-purple-400">02</p>
      <div class="col-span-3">
        <h3 class="text-3xl font-semibold mb-2">Share with anyone</h3>
        <p class="mb-4">
          Share this URL with anyone. It could be a friend, or it could be
          someone you've never met before.
        </p>
      </div>

      <p class="text-8xl font-extrabold mb-4 text-rose-400">03</p>
      <div class="col-span-3">
        <h3 class="text-3xl font-semibold mb-2">Track in real time.</h3>
        <p class="mb-4">
          Use an anonymous identity to protect your privacy. Everyone's
          positions in a location are updated in real-time.
        </p>
      </div>
    </div>
  </div>
</section>

<section class="">
  <div class=" container mx-auto max-w-screen-xl px-4 py-32 ">
    <div class="flex flex-col justify-center items-center w-full text-center">
      <p class="text-lg text-rose-400 font-bold sm:text-2xl mb-4 uppercase">Why Anonymous Location</p>
      <h2 class="text-3xl font-semibold sm:text-5xl">Features</h2>
    </div>

    <div
      class="
        mt-8 grid grid-cols-1 gap-8 md:mt-16 md:grid-cols-2 md:gap-12 lg:grid-cols-2
      "
    >
      <div class="flex items-start gap-4">
        <span class="shrink-0 rounded-lg bg-gray-800 text-white p-4">
          <%= inline_svg "eye-off.svg" %>
        </span>

        <div>
          <h2 class="text-lg font-bold">
            Completely Anonymous.
          </h2>

          <p class="mt-1 text-sm">
            No login or account is required. We don't know your name or email,
            and we don't want to. The only thing we'll ever share is your
            location.
          </p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="shrink-0 rounded-lg bg-gray-800 text-white p-4">
          <%= inline_svg "globe.svg" %>
        </span>
        <div>
          <h2 class="text-lg font-bold">
            Works Everywhere.
          </h2>

          <p class="mt-1 text-sm">
            You don't need an app for that. Anonymous location works on any
            device with a web browser.
          </p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="shrink-0 rounded-lg bg-gray-800 text-white p-4">

          <%= inline_svg "dollar-sign.svg" %>
        </span>
        <div>
          <h2 class="text-lg font-bold">
            Free.
          </h2>

          <p class="mt-1 text-sm">
            Anonymous Location is entirely free to use. No subscriptions, no
            hidden fees.
          </p>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="shrink-0 rounded-lg bg-gray-800 text-white p-4">
          <%= inline_svg "github.svg" %>
        </span>
        <div>
          <h2 class="text-lg font-bold">
            Open Source.
          </h2>

          <p class="mt-1 text-sm">
            Don't believe our claims? That's fine. You can read the source code
            for this product on GitHub. Data Dead Drop is built with love using
            Ruby on Rails.
          </p>
        </div>
      </div>

    </div>
  </div>
</section>

<section>
  <div class="mx-auto max-w-screen-xl px-4 py-32">
    <div
      class="
        grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-16 justify-items-center
        content-center
      "
    >

      <%= image_tag "chat.png",
      class: "rounded inset-0 object-cover h-64 sm:h-80 lg:order-last lg:h-full 0" %>

      <div class="lg:py-24">
        <p class="text-lg text-emerald-400 font-bold sm:text-2xl mb-4 uppercase">Simplify your conversations</p>
        <h2 class="text-3xl font-semibold sm:text-5xl">Just Meet</h2>

        <p class="mt-4 text-white">
          You agreed to meet and decided on a place. But it's not so simple, is
          it? Communication is hard. Avoid exhausting conversations. Simplify
          dates and meet-ups. Just send a link and be done with it.
        </p>

        <%= link_to "Get Started",
        new_location_path,
        class:
          "mt-8 inline-block rounded-full text-gray-900 bg-white px-12 py-3 text-sm font-medium
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   transition focus:outline-none focus:ring
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   focus:ring-fuchsia-400" %>
      </div>
    </div>
  </div>
</section>

app/views/application/legal.html.erb
<section
  id="privacy"
  class="prose container mx-auto max-w-screen-xl pt-16 px-4"
>
  <h2><strong>Privacy Policy</strong></h2>
  <p>
    This app collects no private data, period. Your data will not be used in
    any way, because we won't have it.
  </p>
</section>

app/views/clients/create.turbo_stream.erb
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

<% if @client.persisted? %>
  <%= turbo_stream.remove "form" %>
<% end %>

app/views/layouts/_flash.html.erb
<div
  id="flash"
  class="fixed top-3 left-1/2 transform -translate-x-1/2 w-max z-50"
>
  <% if flash.any? %>
    <div
      class='
        flex flex-col items-end justify-end gap-4 max-w-80 md:max-w-full text-center
      '
    >
      <% flash.each do |flash_type, message| %>
        <div
          data-controller="remove"
          data-action="animationend->remove#remove"
          class="
            flash-message border <%= flash_classes(flash_type.to_sym) %> p-2 rounded
          "
          role="alert"
        >
          <span class="block px-5">
            <%= message %>
          </span>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<title>Anonymous Location</title>

<meta
  name="description"
  content="Share your position with anyone without revealing your identity. Track any number of people. All in real-time."
>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

<%= yield :head %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>

  <body class="h-screen flex flex-col text-white bg-gray-900">
    <header class="bg-gray-900">
      <div class=" mx-auto flex h-16 max-w-screen-xl items-center justify-between px-4 " >

        <div class="flex flex-row justify-center items-center gap-2">
          <%= inline_svg "logo.svg", class: "size-10" %>
          <a class=" flex flex-row gap-1 items-center" href="/">
            <span class="text-xl text-bold font-extrabold">Anonymous Location</span>
          </a>
        </div>
        <a
          class="
            hidden sm:flex text-center justify-center items-center text-gray-800 font-semibold outline-none bg-white rounded-full px-4 py-3
            text-sm focus:outline-none focus:ring sm:w-auto
          "
          href="<%= new_location_path %>"
        >
          Share Location
        </a>

      </div>
    </header>
    <main class="flex-grow">
      <%= yield %>
    </main>
    <footer class="bg-gray-900 ">
      <div class="mx-auto max-w-screen-xl mt-12 py-6 p-4">
        <div class="text-center sm:flex sm:justify-between sm:text-left">
          <p class="mt-4 text-sm sm:order-first sm:mt-0">
            Made with ❤️ by <%= link_to("Hans Schnedlitz", "https://github.com/hschne", class: link_classes) %>
          <ul
          class="
              mt-8 sm:mt-0 flex flex-wrap justify-center gap-4 text-xs lg:justify-end
            "
          >
            <li>
              <a href="/legal#privacy" class="no-underline hover:underline">
                Privacy Policy
              </a>
            </li>
          </ul>

          <ul class="mt-8 flex justify-center gap-6 sm:mt-0 lg:justify-end">
            <li>
              <a
                href="/"
                rel="noreferrer"
                target="_blank"
                class="text-white transition hover:opacity-75"
              >
                <span class="sr-only">Mastodon</span>
                <%= inline_svg "mastodon.svg", class: "h-6 w-6" %>
              </a>
            </li>

            <li>
              <a
                href="https://twitter.com/hschnedlitz"
                rel="noreferrer"
                target="_blank"
                class="text-white transition hover:opacity-75"
              >
                <span class="sr-only">Twitter</span>

                <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path
                    d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"
                  />
                </svg>
              </a>
            </li>

            <li>
              <a
                href="https://github.com/hschne/data-dead-drop"
                rel="noreferrer"
                target="_blank"
                class="text-white transition hover:opacity-75"
              >
                <span class="sr-only">GitHub</span>

                <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                  <path
                    fill-rule="evenodd"
                    d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                    clip-rule="evenodd"
                  />
                </svg>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/locations.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>

    <script
      src="https://cdn.maptiler.com/maptiler-sdk-js/v1.2.0/maptiler-sdk.umd.js"
    ></script>
    <link
      href="https://cdn.maptiler.com/maptiler-sdk-js/v1.2.0/maptiler-sdk.css"
      rel="stylesheet"
    >
    <script
      src="https://cdn.maptiler.com/maptiler-geocoding-control/v1.2.0/maptilersdk.umd.js"
    ></script>
    <link
      href="https://cdn.maptiler.com/maptiler-geocoding-control/v1.2.0/style.css"
      rel="stylesheet"
    >
  </head>

  <body class="h-screen flex flex-col text-gray-800">
    <main class="flex-grow">
      <%= yield %>
      <%= render "layouts/flash" %>
    </main>
  </body>
</html>

app/views/locations/create.turbo_stream.erb
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/locations/expired.html.erb
<div class="w-full h-full grid place-content-center gap-4 bg-white">
  <h1 class="uppercase tracking-widest font-semibold text-gray-700">Location Expired</h1>
  <%= link_to "New Location",
  new_location_path,
  class:
    "shadow rounded py-2 px-3 bg-gray-100 border-gray-500 cursor-pointer justify-center items-center text-center" %>
</div>

app/views/locations/new.html.erb
<section
  data-controller="new-map"
  data-new-map-api-key-value="<%= ENV["MAPTILER_KEY"] %>"
  class="w-full h-screen relative"
>
  <div
    id="spinner"
    role="status"
    class="w-full h-screen flex justify-center items-center"
  >
    <svg
      aria-hidden="true"
      class="
        inline w-8 h-8 text-gray-200 animate-spin dark:text-gray-600 fill-gray-600
        dark:fill-gray-300
      "
      viewBox="0 0 100 101"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
        fill="currentColor"
      />
      <path
        d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
        fill="currentFill"
      />
    </svg>
    <span class="sr-only">Loading...</span>
  </div>
  <div
    class="
      absolute bottom-0 md:bottom-5 left-1/2 transform -translate-x-1/2 z-50 rounded
      shadow p-4 bg-gray-100 w-full md:w-2/3 xl:w-1/2 2xl:w-1/3
    "
  >
    <p class="pb-4">
      Enter a name for your location. Click on the map to set location
      coordinates.
    </p>
    <%= form_with(model: @location, class: "grid grid-cols-1 auto-rows-min items-end md:grid-cols-3 gap-y-1 gap-x-2", data: { 'new-map-target': 'form'}) do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name,
                      class:
                        "block shadow rounded border border-gray-200 outline-none px-2 py-1 w-full md:order-1" %>

      <%= form.label :expiry, "Expiry (in minutes)", class: "md:col-span-2" %>
      <%= form.number_field :expiry,
                        class:
                          "block shadow rounded border border-gray-200 outline-none px-2 py-1 w-full md:order-1" %>

      <%= form.hidden_field :location %>

      <%= form.submit class:
                    "mt-2 inline-block shadow rounded py-2 px-3 bg-white border-gray-500 cursor-pointer self-end md:order-last disabled:opacity-50 disabled:cursor-not-allowed",
                  disabled: true,
                  id: "new_map_submit" %>
    <% end %>
  </div>
</section>